version: '3'
services:
  chessdb:
    image: timescale/timescaledb:latest-pg16
    restart: always
    ports:
      - 5432:5432
    #networks:
      #- chess_backend
    environment:
      - POSTGRES_PASSWORD=${PG_PASS}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db_schema.sql:/docker-entrypoint-initdb.d/db_schema.sql #initalize preset schema on container start

  adminer:
    image: adminer
    ports:
      - 8080:8080
    

#networks:
  #chess_backend:

volumes:
  pgdata: