version: '3'
services:
  chessdb:
    image: timescale/timescaledb:latest-pg16
    restart: always
    ports:
      - 5432:5432
    #networks:
      #- chess_backend
    environment:
      - POSTGRES_PASSWORD=${PG_PASS}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./dbMigrations/initialSchema.sql:/docker-entrypoint-initdb.d/initialSchema.sql #initalize preset schema on container start

  adminer:
    image: adminer
    ports:
      - 8080:8080
    
  grafana:
    image: grafana/grafana-oss
    restart: unless-stopped
    ports:
      - 3001:3000
    volumes: 
      - grafanaStore:/var/lib/grafana

#networks:
  #chess_backend:

volumes:
  pgdata:
  grafanaStore:
